### ISSUE TITLE
获取群昵称中包含的中文显示问题

### ISSUE THREAD

**Issue by jzcangshu** [jzcangshu/ZF_Lottery_Bot#9]
目前spider.py获取的群昵称中一旦包含中文，就会显示为 `\u5c4a\u65b0\u751f\u4ea4\u6d41\u4f1a` 格式

@Rea1-ms 帮我康康，不知换用哪种编码格式或者使用什么方法可以解决这一问题？

**Comment by Rea1-ms** [comment]
chatgpt说用Unicode

**Comment by Rea1-ms** [comment]
以下是回答：这是Unicode编码的表示方式，\u后面跟着4个十六进制数字，表示一个Unicode字符的编码。例如，\u5c4a表示的是Unicode编码为"届"的字符，\u65b0表示的是Unicode编码为"新"的字符。在Python中，字符串中使用Unicode编码时，可以使用这种表示方式来表示Unicode字符。例如，"\u5c4a\u65b0\u751f\u4ea4\u6d41\u4f1a"可以表示为"届新生交流会"，这是一个由五个汉字组成的字符串，表示一个新生交流会的名称。

**Comment by jzcangshu** [comment]
好像保存到TXT里自动就好了...那先不管了
